import { env } from "node:process";

const metadata = {
    access_token: null as string | null,
    user_access_token: null as string | null
}

let initPromise: Promise<string | null> | null = null

export default async function initializeMSAccessToken() {

    console.log("[MSGraph] Initializing MS Access Token...")

    if (metadata.access_token) {
        console.log("MS Access Token already initialized")
        return metadata.access_token;
    }

    const req = await fetch("https://login.microsoftonline.com/cbc6e1e2-a6bb-4002-bbdc-6da892a051a7/oauth2/v2.0/token",{
        method: "POST",
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded'
        },
        body: encodeURI(
            "client_id=868b989e-6574-4795-bcfb-8db37bee1c37&" +
            "scope=https://graph.microsoft.com/.default&" +
            "client_secret=" + env.MICROSOFT_CLIENT_SECRET + "&" +
            "grant_type=client_credentials"
        )
    })

    const code = req.status
    if (code !== 200) {
      console.warn(`[MS Graph] MS Token Endpoint returned ${code} - Microsoft Graph features will be unavailable`)
      return null
    } else {
        console.log("[MSGraph] API Endpoint response: " + code)
    }
    const data: any = await req.json()
    return metadata.access_token = data.access_token
}

export async function getMSAccessToken() {
    if (!initPromise) {
        initPromise = initializeMSAccessToken()
    }
    const token = await initPromise
    if (!token) {
        throw new Error("[MS Graph] MS Access Token not initialized")
    }
    return token;
}

/*
 SECURITY POLICY: All microsoft graph related API MUST BE CALLED IN THIS FILE.
 If you need any api usage, create a wrapper inside this function and export it.
 */

async function requestMicrosoft(endpoint: string, method: string = "GET", body: any = null) {

    const res = await fetch("https://graph.microsoft.com/v1.0" + endpoint, {
        method,
        headers: {
            "Content-Type": "application/json",
            "Authorization": "Bearer " + await getMSAccessToken()
        },
        body
    });

    return res;
}

export async function createMicrosoftMeeting(target: string, subject: string, htmlDescription: string, startTime: string, endTime: string, attendees: any[]): Promise<Response> {

    const disclaimer = `<br><br><hr><p style='font-size:10pt;color:gray;'><i>This event was auto-generated by basishacks. If you believe this was scheduled in error or need to reschedule, please feel free to direct message devclub-bisz@basischina.com and your message will be fowarded to the necessary person.</i></p>`

    const body = JSON.stringify({
        "subject": subject,
        "body" : {
            "contentType": "HTML",
            "content": htmlDescription + disclaimer
        },
        "start": {
            "dateTime": startTime,
            "timeZone": "UTC"
        },
        "end": {
            "dateTime": endTime,
            "timeZone": "UTC"
        },
        "attendees": attendees.map(email => ({
            "emailAddress": {
                "address": email
            }
        }))
    });

    const res = await requestMicrosoft("/users/" + target + "/events", "POST", body);

    return res; // Created
}

export async function initializeDummyUserAccessToken() {

    const res = await fetch("https://login.microsoftonline.com/cbc6e1e2-a6bb-4002-bbdc-6da892a051a7/oauth2/v2.0/token", {
        method: "POST",
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded'
        },
        body: encodeURI(
            "client_id=868b989e-6574-4795-bcfb-8db37bee1c37&" +
            "scope=https://graph.microsoft.com/Chat.ReadWrite openid profile offline_access" + "&" +
            "username=" + env.MICROSOFT_DUMMY_USER_NAME + "&" +
            "password=" + env.MICROSOFT_DUMMY_USER_PASSWORD + "&" +
            "grant_type=password&" +
            "client_secret=" + env.MICROSOFT_CLIENT_SECRET
        )
    });

    const data: any = await res.json();
    console.log("Response from Dummy User Token Endpoint: " + JSON.stringify(data));

    metadata.user_access_token = data.access_token;

    return data.access_token;
}

export function getDummyUserAccessToken() {
    if (!metadata.user_access_token) {
        throw new Error("Dummy User Access Token not initialized")
    }
    return metadata.user_access_token;
}
