import { createHash, randomBytes } from "node:crypto";
import { env } from "node:process";
import { ObjectType } from "typescript";
import { structureLink } from "~~/shared/oauth2";

const metadata = {
    access_token: null as string | null,
    user_access_token: null as string | null | undefined,
    user_refresh_token: null as string | null | undefined,
    webhook_state: null as string | null,
    webhook_id: null as string | null
}

let initPromise: Promise<string | null> | null = null

export default async function initializeMSAccessToken() {

    console.log("[MSGraph] Initializing MS Access Token...")

    if (metadata.access_token) {
        console.log("MS Access Token already initialized")
        return metadata.access_token;
    }

    const req = await fetch("https://login.microsoftonline.com/cbc6e1e2-a6bb-4002-bbdc-6da892a051a7/oauth2/v2.0/token",{
        method: "POST",
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded'
        },
        body: encodeURI(
            "client_id=868b989e-6574-4795-bcfb-8db37bee1c37&" +
            "scope=https://graph.microsoft.com/.default&" +
            "client_secret=" + env.MICROSOFT_CLIENT_SECRET + "&" +
            "grant_type=client_credentials"
        )
    })

    const code = req.status
    if (code !== 200) {
      console.warn(`[MS Graph] MS Token Endpoint returned ${code} - Microsoft Graph features will be unavailable`)
      return null
    } else {
        console.log("[MSGraph] API Endpoint response: " + code)
    }
    const data: any = await req.json()
    return metadata.access_token = data.access_token
}

export async function getMSAccessToken() {
    if (!initPromise) {
        initPromise = initializeMSAccessToken()
    }
    const token = await initPromise
    if (!token) {
        throw new Error("[MS Graph] MS Access Token not initialized")
    }
    return token;
}

/*
 SECURITY POLICY: All microsoft graph related API MUST BE CALLED IN THIS FILE.
 If you need any api usage, create a wrapper inside this function and export it.
 */

async function requestMicrosoft(endpoint: string, method: string = "GET", body: string | Object | null = null) {

    const res = await fetch("https://graph.microsoft.com/v1.0" + endpoint, {
        method,
        headers: {
            "Content-Type": "application/json",
            "Authorization": "Bearer " + await getMSAccessToken()
        },
        body: typeof body === "string" ? body : JSON.stringify(body)
    });

    return res;
}

async function requestUserMicrosoft(endpoint: string, method: string = "GET", body: string | Object | null = null) {

    const res = await fetch("https://graph.microsoft.com/v1.0" + endpoint, {
        method,
        headers: {
            "Content-Type": "application/json",
            "Authorization": "Bearer " + getDummyUserAccessToken()
        },
        body: typeof body === "string" ? body : JSON.stringify(body)
    });

    if (res.status == 401) {
        console.warn("[MS Graph] User token unauthorized, refreshing dummy user access token...")
        metadata.user_access_token = null
        await initializeDummyUserAccessToken()
        return requestUserMicrosoft(endpoint, method, body)
    }

    return res;
}

export async function createMicrosoftMeeting(target: string, subject: string, htmlDescription: string, startTime: string, endTime: string, attendees: any[]): Promise<Response> {

    const disclaimer = `<br><br><hr><p style='font-size:10pt;color:gray;'><i>This event was auto-generated by basishacks. If you believe this was scheduled in error or need to reschedule, please feel free to direct message devclub-bisz@basischina.com and your message will be fowarded to the necessary person.</i></p>`

    const body = JSON.stringify({
        "subject": subject,
        "body" : {
            "contentType": "HTML",
            "content": htmlDescription + disclaimer
        },
        "start": {
            "dateTime": startTime,
            "timeZone": "UTC"
        },
        "end": {
            "dateTime": endTime,
            "timeZone": "UTC"
        },
        "attendees": attendees.map(email => ({
            "emailAddress": {
                "address": email
            }
        }))
    });

    const res = await requestMicrosoft("/users/" + target + "/events", "POST", body);

    return res; // Created
}

export async function initializeDummyUserAccessToken() {

    const res = await fetch("https://login.microsoftonline.com/cbc6e1e2-a6bb-4002-bbdc-6da892a051a7/oauth2/v2.0/token", {
        method: "POST",
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded'
        },
        body: encodeURI(
            "client_id=868b989e-6574-4795-bcfb-8db37bee1c37&" +
            "scope=https://graph.microsoft.com/Chat.ReadWrite openid profile offline_access" + "&" +
            "username=" + env.MICROSOFT_DUMMY_USER_NAME + "&" +
            "password=" + env.MICROSOFT_DUMMY_USER_PASSWORD + "&" +
            "grant_type=password&" +
            "client_secret=" + env.MICROSOFT_CLIENT_SECRET
        )
    });

    const data: any = await res.json();

    

    console.log("[MS Graph] Response from Dummy User Token Endpoint: " + res.status + " Token:" + (data.access_token as string).substring(0, 20) + "..." + " Refresh Token:" + (data.refresh_token as string).substring(0, 20) + "...");

    if (res.status == 400) {

        const state = randomBytes(77).toString("base64url")
        const code_verif = randomBytes(75).toString("base64url")
        const code_challenge = createHash("sha256").update(code_verif).digest("base64url")
        const link = structureLink(state, code_challenge, encodeURI("Chat.Create Chat.ReadWrite Presence.ReadWrite"))

        console.log("[MS Graph] Dummy user error: " + data.error_description)
        console.log("[MS Graph] Consent first with DevClub User: " + link)
    }

    metadata.user_access_token = data.access_token as string | undefined
    metadata.user_refresh_token = data.refresh_token as string | undefined


    return data.access_token;
}

// In-memory cache: target user id -> chat id
// One-on-one chats are stable, so we keep them for the lifetime of the process.
const directChatCache = new Map<string, string>()

/*
 * Creates or retrieves an existing direct chat with the dummy user, and returns the chat ID.
 * Cached in-memory to avoid repeated Microsoft Graph requests for the same target.
*/
export async function createOrGetExistingDirectChat(targetId: string): Promise<{ id: string }> {
    const cached = directChatCache.get(targetId)
    if (cached) {
        return { id: cached }
    }

    const res = await requestUserMicrosoft("/chats", "POST", JSON.stringify({
        "chatType": "oneOnOne",
        "members": [
            {
                "@odata.type": "#microsoft.graph.aadUserConversationMember",
                "roles": ["owner"],
                "user@odata.bind": "https://graph.microsoft.com/v1.0/users('" + process.env.MICROSOFT_DUMMY_USER_NAME + "')"
            },
            {
                "@odata.type": "#microsoft.graph.aadUserConversationMember",
                "roles": ["owner"],
                "user@odata.bind": "https://graph.microsoft.com/v1.0/users('" + targetId + "')"
            }
        ]
    }))

    const data = await res.json()

    if (!res.ok) {
        throw createError({
            statusCode: res.status,
            message: data.error?.message || 'Failed to create or retrieve direct chat'
        })
    }

    const chatId = data.id as string
    if (!chatId) {
        throw createError({
            statusCode: 500,
            message: 'Microsoft Graph response missing chat id'
        })
    }

    directChatCache.set(targetId, chatId)
    return { id: chatId }
}

export function getDummyUserAccessToken() {
    if (!metadata.user_access_token) {
        throw new Error("[MS Graph] Dummy User Access Token not initialized")
    }
    return metadata.user_access_token;
}

export async function sendChatMessage(chatId: string, content: string) {
    const res = await requestUserMicrosoft("/chats/" + chatId + "/messages", "POST", JSON.stringify({
        "body": {
            "contentType": "text",
            "content": content
        }
    }))
    return res;
}

export async function sendRichChatMessage(chatId: string, content: string) {
    const res = await requestUserMicrosoft("/chats/" + chatId + "/messages", "POST", JSON.stringify({
        "body": {
            "contentType": "html",
            "content": content
        }
    }))
    return res;
}

export function getMicrosoftWebhookState() {
    return metadata.webhook_state;
}

export async function refreshChatbotWebhook() {
    console.log("[MS Graph] Refreshing chatbot webhook subscription... " + getChatbotWebhookId())

    if (process.env.CURRENT_URL_ORIGIN == null || process.env.CURRENT_URL_ORIGIN.startsWith("http://localhost")) {
        console.warn("[MS Graph] CURRENT_URL_ORIGIN is not set or is a localhost URL.")
        return
    }

    const res = await requestUserMicrosoft("/subscriptions/" + getChatbotWebhookId(), "PATCH", {
        "expirationDateTime": new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 days from now
    })

    console.log("[MS Graph] Refresh response: " + res.status)
}

export async function initializeChatbotWebhook() {

    if (process.env.CURRENT_URL_ORIGIN == null || process.env.CURRENT_URL_ORIGIN.startsWith("http://localhost")) {
        console.warn("[MS Graph] CURRENT_URL_ORIGIN is not set or is a localhost URL.")
        return
    }

    console.log("[MS Graph] Initializing chatbot webhook subscription...")

    metadata.webhook_state = randomBytes(89).toString("base64url")

    const res = await requestUserMicrosoft("/subscriptions", "POST", {
        "changeType": "created,updated",
        "notificationUrl": process.env.CURRENT_URL_ORIGIN + "/api/_webhooks/update",
        "lifecycleNotificationUrl": process.env.CURRENT_URL_ORIGIN + "/api/_webhooks/lifecycle",
        "resource": "/chats/getAllMessages",
        "expirationDateTime": new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 days from now
        "clientState": metadata.webhook_state
    })

    if (!res.ok) {
        const errorData = await res.json()
        console.warn("[MS Graph] Failed to create chatbot webhook subscription:", res.status, errorData)
        return
    }

    const json = await res.json()
    const subId = json.id
    metadata.webhook_id = subId;

    console.log("[MS Graph] Created webhook " + subId + "expr:" + json.expirationDateTime)
}

export function getChatbotWebhookId() {
    return metadata.webhook_id;
}