-- this file is generated by chatgpt because i can't sql

PRAGMA defer_foreign_keys = ON;

------------------------------------------------------------
-- 1. Rename old table
------------------------------------------------------------

ALTER TABLE ballots RENAME TO ballots_old;
DROP INDEX idx_ballots_user_id;

------------------------------------------------------------
-- 2. Create new ballots table
------------------------------------------------------------

CREATE TABLE ballots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    reasoning TEXT,
    submitted INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE UNIQUE INDEX idx_ballots_user_id ON ballots (user_id);

------------------------------------------------------------
-- 3. Create ballot_scores table
------------------------------------------------------------

CREATE TABLE ballot_scores (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ballot_id INTEGER NOT NULL,
    project_id INTEGER NOT NULL,
    score INTEGER CHECK (score IN (NULL, 1, 2, 3, 4, 5)),
    FOREIGN KEY (ballot_id) REFERENCES ballots(id) ON DELETE CASCADE
);

CREATE INDEX idx_ballot_scores_project_id
    ON ballot_scores (project_id);

CREATE INDEX idx_ballot_scores_ballot_id
    ON ballot_scores (ballot_id);

CREATE UNIQUE INDEX idx_unique_ballot_project
    ON ballot_scores (ballot_id, project_id);

------------------------------------------------------------
-- 4. Copy ballot metadata
--    submitted = 0 if scores IS NULL
--    submitted = 1 otherwise
------------------------------------------------------------

INSERT INTO ballots (id, user_id, reasoning, submitted)
SELECT
    id,
    user_id,
    reasoning,
    CASE
        WHEN scores IS NULL THEN 0
        ELSE 1
    END
FROM ballots_old;

------------------------------------------------------------
-- 5. Migrate JSON arrays into ballot_scores
--    If scores IS NULL → score becomes NULL
------------------------------------------------------------

INSERT INTO ballot_scores (ballot_id, project_id, score)
SELECT
    b.id,
    json_extract(p.value, '$') AS project_id,
    CASE
        WHEN b.scores IS NULL THEN NULL
        ELSE json_extract(s.value, '$')
    END AS score
FROM ballots_old b
JOIN json_each(b.projects) p
LEFT JOIN json_each(b.scores) s
    ON p.key = s.key;

------------------------------------------------------------
-- 6. Drop old table
------------------------------------------------------------

DROP TABLE ballots_old;
